# Auto-generated Terraform — test4
# Generated by AI Infrastructure Agent

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {
    bucket         = "test4-tf-state"
    key            = "test4/terraform.tfstate"
    region         = "ap-south-1"
    dynamodb_table = "test4-tf-lock"
  }
}

provider "aws" {
  region = "ap-south-1"

  default_tags {
    tags = {
      Project   = "test4"
      ManagedBy = "terraform"
    }
  }
}




# ── EC2 ───────────────────────────────────────────────────────────
resource "aws_instance" "app" {
  ami           = "ami-0f58b397bc5c1f2e8"  # Amazon Linux 2 — Mumbai
  instance_type = "t2.micro"

  

  tags = { Name = "test4-server" }
}

output "ec2_public_ip" {
  value       = aws_instance.app.public_ip
  description = "Public IP of the EC2 instance"
}



# ── S3 ────────────────────────────────────────────────────────────
resource "random_id" "suffix" {
  byte_length = 4
}

resource "aws_s3_bucket" "app_bucket" {
  bucket = "test4-storage-${random_id.suffix.hex}"
  tags   = { Name = "test4-bucket" }
}

resource "aws_s3_bucket_versioning" "versioning" {
  bucket = aws_s3_bucket.app_bucket.id
  versioning_configuration {
    status = "Enabled"
  }
}

output "s3_bucket_name" {
  value       = aws_s3_bucket.app_bucket.bucket
  description = "Name of the S3 bucket"
}










